CREATE SCHEMA IF NOT EXISTS desafio;
-- desafio.clientes definition

-- Drop table

-- DROP TABLE desafio.clientes;

CREATE TABLE IF NOT EXISTS desafio.clientes (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	cpf varchar(14) NOT NULL,
	email varchar(100) NOT NULL,
	nome varchar(100) NOT NULL,
	observacoes text NULL,
	cor_preferida_id int8 NOT NULL,
	CONSTRAINT clientes_pkey PRIMARY KEY (id),
	CONSTRAINT uk1c96wv36rk2hwui7qhjks3mvg UNIQUE (email),
	CONSTRAINT uk7wflw78ibh162cmq12ii6ffly UNIQUE (cpf)
);

-- desafio.cores definition

-- Drop table

-- DROP TABLE desafio.cores;

CREATE TABLE IF NOT EXISTS  desafio.cores (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	nome varchar(20) NOT NULL,
	CONSTRAINT cores_pkey PRIMARY KEY (id),
	CONSTRAINT ukliux7664pmoqnm2y8b5itbrbe UNIQUE (nome)
);

-- desafio.clientes foreign keys

ALTER TABLE desafio.clientes ADD CONSTRAINT fkmurqrl39heurlbm9lm7mt0dm7 FOREIGN KEY (cor_preferida_id) REFERENCES desafio.cores(id);


INSERT INTO desafio.cores(nome) VALUES
('Vermelho'),
('Laranja'),
('Amarelo'),
('Verde'),
('Azul'),
('Anil'),
('Violeta');